display_name: FlClash-EE

icon: ./assets/images/icon.png

keywords:
  - FlClash-EE
  - Clash
  - ClashMeta
  - Proxy

generic_name: FlClash-EE

categories:
  - Network

startup_notify: true

include: []