script_template: inno_setup.iss
app_id: A1B2C3D4-E5F6-7890-ABCD-EF1234567890
app_name: FlClash-EE
publisher: zxc135781
publisher_url: https://github.com/zxc135781/FlClash
display_name: FlClash-EE
executable_name: FlClash-EE.exe
output_base_file_name: FlClash-EE.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin
